---
all:
  children:
    # Management infrastructure
    management:
      hosts:
        janus:
          ansible_host: 192.168.100.5

    # Network infrastructure
    gateways:
      hosts:
        porta:
          ansible_host: 192.168.100.1

    # Certificate Authority
    ca_servers:
      children:
        ca_master:
          hosts:
            marcus:
              ansible_host: 192.168.100.10
        ca_intermediate:
          hosts:
            tiberius:
              ansible_host: 192.168.100.11

    # DNS servers
    dns_servers:
      children:
        dns_primary:
          hosts:
            titus:
              ansible_host: 192.168.100.20
        dns_secondary:
          hosts:
            claudia:
              ansible_host: 192.168.100.21

    # DHCP servers
    dhcp_servers:
      children:
        dhcp_primary:
          hosts:
            titus:
              ansible_host: 192.168.100.20
        dhcp_secondary:
          hosts:
            claudia:
              ansible_host: 192.168.100.21

    # Grouped by function
    infrastructure:
      children:
        gateways:
        dns_servers:
        dhcp_servers:
        ca_servers:

  vars:
    ansible_user: rdodswor
    ansible_become: yes
    ansible_become_method: sudo
